import {Persona} from "../classes/persona.class";

export const personas: Persona[] = [
  {id:1,arcana:"Fool",name:"Arsene",lvl:1,weaknesses:['','','','Wk','','','','','Wk','Str'],description:"A being based off the main character of Maurice Leblanc's novels, Arsene Lupin. He appears everywhere and is a master of disguise. He is known to help law-abiding citizens."},
  {id:2,arcana:"Fool",name:"Obariyon",lvl:8,weaknesses:['Str','','','','Wk','','','','',''],description:"A 'piggyback monster' of Japan that jumps on the backs of those who pass grassy paths. It is heavy and not easily removed, but will turn into gold coins if you can carry it back home."},
  {id:3,arcana:"Fool",name:"High Pixie",lvl:16,weaknesses:['','Wk','','','Str','Str','','Wk','',""],description:"The leader of a swarm of pixies. Any pixie in a leadership role or with remarkable power is called by this name."},
  {id:4,arcana:"Fool",name:"Inzanagi",lvl:20,weaknesses:['','','','','Nul','Wk','','','',"Nul"],description:"A Persona of another story. One of the ancient gods who existed before Japan was formed. He created the Oyashima from chaos, then gave birth to countless children."},
  {id:5,arcana:"Fool",name:"Inzanagi Picaro",lvl:23,weaknesses:['','','','','Nul','Wk','','','',"Nul"],description:"A Persona turned picaro afther becoming the trickster's mask. One of the ancient gods who existed before Japan was formed. He created the Oyashima from chaos, then gave birth to countless children."},
  {id:6,arcana:"Fool",name:"Orpheus",lvl:26,weaknesses:['','','','','Wk','','','','Str',"Wk"],description:"A Persona of another story. A poet skilled with the lyre. He tried to retrieve his wife from Hades, but she vanished when he looked back before reaching the surface."},
  {id:7,arcana:"Fool",name:"Orpheus Picaro",lvl:29,weaknesses:['','','','','Wk','','','','Str',"Wk"],description:"A Persona turned picaro afther becoming the trickster's mask. A Greek poet who tried to retrieve his wife from Hades, but she vanished when he looked back before reaching the surface."},
  {id:8,arcana:"Fool",name:"Decarabia",lvl:32,weaknesses:['Wk','','Rpl','','','','','Str','',"Str"],description:"One of the 72 demons of Goetia, this demon appears as a pentacle. Keeper of jewels and herval lore, Decarabia is said to have the ability to shape-shift at will."},
  {id:9,arcana:"Fool",name:"Legion",lvl:38,weaknesses:['Str','Str','Str','','','','Str','','Wk',"Nul"],description:"The spirit who said, 'For we are many.' in ancient scriptures. The name comes from the Roman military term for an army unit of 3,000 to 6,000 men."},
  {id:10,arcana:"Fool",name:"Ose",lvl:42,weaknesses:['','','Str','','','','','','Wk',"Nul"],description:"One of the 72 demons of the Goetia, he is known as the President of Hell. He can shape-shift from leopard to human and reveal the truth behind divine mysteries."},
  {id:11,arcana:"Fool",name:"Bugs",lvl:49,weaknesses:['','','','','','','Str','Wk','',"Nul"],description:"A Welsh creature commonly known as 'Bugbear' or the 'Boogeyman'. Its existence is often used by mothers to scare children into behaving."},
  {id:12,arcana:"Fool",name:"Crystal Skull",lvl:50,weaknesses:['Str','Nul','Rpl','Rpl','Rpl','Rpl','Rpl','Rpl','',"Rpl"],description:"An ancient Out-Of-Place-Artifact found in Central and South America. It is said that if you collect 13 of them in one spot, the truth of the universe will be revealed."},
  {id:13,arcana:"Fool",name:"Dionysus",lvl:61,weaknesses:['','','','','Rpl','','','','Str',"Str"],description:"The Greek god of wine and theater. He was originally a god of life protecting the mountains of Thrace. He taught humans how to make wine."},
  {id:14,arcana:"Fool",name:"Black Frost",lvl:67,weaknesses:['','','Rpl','Dr','','','','Nul','',"Rpl"],description:"A Jack Frost that yearned for evil. This powerful demon is born when a cute Jack Frost remembers its nature as a demon."},
  {id:15,arcana:"Fool",name:"Vishnu",lvl:83,weaknesses:['','','Wk','Dr','','','','','Nul',"Nul"],description:"One of the major Hindu gods, he is the preserver and protector of the universe. Legends claim that he will make then appearances across time and space to strike down evil and uphold justice."},
  {id:16,arcana:"Fool",name:"Satanael",lvl:95,weaknesses:['Str','Str','Str','Str','Str','Str','Str','Str','Str',"Dr"],description:"An archangel who is said to be the form of Satan before he fell from Heaven. The second son of God, he rebelled against Him for freedom and bestowed free will and chaos upon humanity."},
  {id:17,arcana:"Magician",name:"Jack-o'-lantern",lvl:2,weaknesses:['','Wk','Dr','Wk','','Wk','','','',''],description:"A drunkard who tricked the Devil out of taking him to Hell. When refused entry to Heaven, he was forced to wander the earth with only an ember as a light."},
  {id:18,arcana:"Magician",name:"Jack Frost",lvl:12,weaknesses:['','','Wk','Nul','','','','','',''],description:"A winter fairy of European descent. He leaves ice patterns on windows and nips people's noses. Though normally an innocent creature, he will freeze his victims to death if provoked"},
  {id:19,arcana:"Magician",name:"Nekomata",lvl:18,weaknesses:['','','','','Wk','','Str','','',''],description:"Long-lived cats are said to become these malevolent cat demons. Their powers vary accrding to how long they have lived, ranging from shape-shifting to controlling the dead."},
  {id:20,arcana:"Magician",name:"Sandman",lvl:24,weaknesses:['','','','','Wk','Str','','','',''],description:"A fairy in German folklore who carries a bag of magical sand, which puts humans to sleep when thrown into their eyes. If the victim resists, the Sandman will sit on their eyelids."},
  {id:21,arcana:"Magician",name:"Choronzon",lvl:30,weaknesses:['','','Dr','','','','','','Wk',''],description:"A demon summoned by a sorcerer named Crowley at the beginning of the 20th century. He prevents those from attempting to reach enlightment."},
  {id:22,arcana:"Magician",name:"Queen Mab",lvl:43,weaknesses:['','','Nul','','Str','Wk','','','',''],description:"A fairy queen in Celtic myth. Often identified with Titania. She would offer mead mixed with her blood to her many consorts."},
  {id:23,arcana:"Magician",name:"Rangda",lvl:48,weaknesses:['Rpl','Rpl','Nul','','Wk','','','','Wk','Nul'],description:"A wicked witch of Balinese lore, she represents evil and is Barong's eternal rival. Even if defeated, she will come back to life, and their battle will have no end."},
  {id:24,arcana:"Magician",name:"Surt",lvl:63,weaknesses:['','','Dr','Wk','','','','','',''],description:"A fire giant in Norse lore. He rules the fire realm, Muspelheim, and brandishes a burning sword. At Ragnarok, he will set the world ablaze."},
  {id:25,arcana:"Magician",name:"Futsunushi",lvl:80,weaknesses:['Str','','','','','','','Wk','',''],description:"The Nishonshoki sword deity who pacified Ashihara-no-Nakatsukuni. His name comes from 'futsi,' the fashion in which things are cut, and 'nushi,' his nature as a god."},
];

const test: Persona[] = [
  {id:17,arcana:"Magician",name:"Jack-o'-lantern",lvl:2,weaknesses:['','Wk','Dr','Wk','','Wk','','','',''],description:"A drunkard who tricked the Devil out of taking him to Hell. When refused entry to Heaven, he was forced to wander the earth with only an ember as a light."},
  {id:18,arcana:"Magician",name:"Jack Frost",lvl:12,weaknesses:['','','Wk','Nul','','','','','',''],description:"A winter fairy of European descent. He leaves ice patterns on windows and nips people's noses. Though normally an innocent creature, he will freeze his victims to death if provoked"},
  {id:19,arcana:"Magician",name:"Nekomata",lvl:18,weaknesses:['','','','','Wk','','Str','','',''],description:"Long-lived cats are said to become these malevolent cat demons. Their powers vary accrding to how long they have lived, ranging from shape-shifting to controlling the dead."},
  {id:20,arcana:"Magician",name:"Sandman",lvl:24,weaknesses:['','','','','Wk','Str','','','',''],description:"A fairy in German folklore who carries a bag of magical sand, which puts humans to sleep when thrown into their eyes. If the victim resists, the Sandman will sit on their eyelids."},
  {id:21,arcana:"Magician",name:"Choronzon",lvl:30,weaknesses:['','','Dr','','','','','','Wk',''],description:"A demon summoned by a sorcerer named Crowley at the beginning of the 20th century. He prevents those from attempting to reach enlightment."},
  {id:22,arcana:"Magician",name:"Queen Mab",lvl:43,weaknesses:['','','Nul','','Str','Wk','','','',''],description:"A fairy queen in Celtic myth. Often identified with Titania. She would offer mead mixed with her blood to her many consorts."},
  {id:23,arcana:"Magician",name:"Rangda",lvl:48,weaknesses:['Rpl','Rpl','Nul','','Wk','','','','Wk','Nul'],description:"A wicked witch of Balinese lore, she represents evil and is Barong's eternal rival. Even if defeated, she will come back to life, and their battle will have no end."},
  {id:24,arcana:"Magician",name:"Surt",lvl:63,weaknesses:['','','Dr','Wk','','','','','',''],description:"A fire giant in Norse lore. He rules the fire realm, Muspelheim, and brandishes a burning sword. At Ragnarok, he will set the world ablaze."},
  {id:25,arcana:"Magician",name:"Futsunushi",lvl:80,weaknesses:['Str','','','','','','','Wk','',''],description:"The Nishonshoki sword deity who pacified Ashihara-no-Nakatsukuni. His name comes from 'futsi,' the fashion in which things are cut, and 'nushi,' his nature as a god."},
  {id:26,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:27,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:28,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:29,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:30,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:31,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:32,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:33,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:34,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:35,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:36,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:37,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:38,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:39,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:40,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:41,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:42,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:43,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:44,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:45,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:46,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
  {id:47,arcana:"",name:"",lvl:0,weaknesses:[""],description:""},
]